# .scrutinizer.yml
checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: ['src/*']
    
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

build:
    environment:
       php: 7.0.8
    tests:
            override:
                -
                    command: 'phpunit --coverage-clover=linna.xml --bootstrap src/bootstrap_test.php tests/'
                    coverage:
                        file: 'linna.xml'
                        format: 'clover'