language: php
php:
- 7.0
- 7.1
- 7.2
- nigthly

matrix:
  allow_failures:
  - php: nigthly
  - php: 7.2

services:
- mysql
- memcached
- mongodb

before_install:
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
- mysql -e 'create database linna_db;'
- mysql -u root linna_db < tests/linna_db_mysql.sql
- composer install
- wget https://github.com/infection/infection/releases/download/0.6.0/infection.phar
- wget https://github.com/infection/infection/releases/download/0.6.0/infection.phar.pubkey
- chmod +x infection.phar

script: 
- phpunit
- ./infection.phar --min-msi=48 --threads=4
