language: php
php:
- 7.0
- 7.1
- hhvm-3.12

matrix:
  allow_failures:
  - php: 7.1
  - php: hhvm-3.12

services:
- mysql
- memcached  

before_script:
- if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
- mysql -e 'create database test;'
- mysql -u root test < tests/database.sql
- phpunit --self-update
- if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then composer require codeclimate/php-test-reporter --dev; fi
- if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then composer install; fi

script: 
- phpunit --coverage-clover build/logs/clover.xml

after_script:
- if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then CODECLIMATE_REPO_TOKEN="73843c11688645a6d15a453cc9259f18c0717933b7e12081a6e849e5eaad46d9" vendor/bin/test-reporter; fi
