language: php
php:
- 7.0.21
- 7.1
- 7.2
- master

matrix:
  allow_failures:
  - php: master
  - php: 7.2

services:
- mysql
- memcached
- mongodb

before_install:
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
- mysql -e 'create database linna_db;'
- mysql -u root linna_db < tests/linna_db_mysql.sql
- composer install --no-dev

script: 
- phpunit
