language: php
php:
- 7.0
- 7.1

services:
- mysql
  

before_script: 
- mysql -e 'create database test;'
- "composer require codeclimate/php-test-reporter --dev"
- "composer install"

script: 
- "phpunit --coverage-clover build/logs/clover.xml"

after_script:
- CODECLIMATE_REPO_TOKEN="73843c11688645a6d15a453cc9259f18c0717933b7e12081a6e849e5eaad46d9" vendor/bin/test-reporter